version: "3.7"

services:
  nginx-cacher:
    container_name: debian-cache
    image: evindunn/nginx-cacher
    ports: [8080:80]
    volumes:
      - ./docker/config:/docker-config
      - ./docker/cache:/var/cache/nginx

